# -*- coding: utf-8 -*-
"""time_modified.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvyDQvnwC_oVekOzxuLACBqgpb_3QqjQ
"""

import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from matplotlib import rc

patientinfo = pd.read_csv('./drive/My Drive/Colab Notebooks/Warmingup_Project/corona_visualization/PatientInfo.csv')
time = pd.read_csv('./drive/My Drive/Colab Notebooks/Warmingup_Project/corona_visualization/Time.csv')

time

test_new_list, negative_new_list, confirmed_new_list, released_new_list, deceased_new_list = list(), list(), list(), list(), list()
for i in range(len(time['test'])):
    if i == 0:
        test_new_list.append(time['test'][0])
    else:
        j = time['test'][i] - time['test'][i-1]
        test_new_list.append(j)

for i in range(len(time['negative'])):
    if i == 0:
        negative_new_list.append(time['negative'][0])
    else:
        j = time['negative'][i] - time['negative'][i-1]
        negative_new_list.append(j)

for i in range(len(time['confirmed'])):
    if i == 0:
        confirmed_new_list.append(time['confirmed'][0])
    else:
        j = time['confirmed'][i] - time['confirmed'][i-1]
        confirmed_new_list.append(j)

for i in range(len(time['released'])):
    if i == 0:
        released_new_list.append(time['released'][0])
    else:
        j = time['released'][i] - time['released'][i-1]
        released_new_list.append(j)

for i in range(len(time['deceased'])):
    if i == 0:
        deceased_new_list.append(time['deceased'][0])
    else:
        j = time['deceased'][i] - time['deceased'][i-1]
        deceased_new_list.append(j)

time['test_new'] = test_new_list
time['negative_new'] = negative_new_list
time['confirmed_new'] = confirmed_new_list
time['released_new'] = released_new_list
time['deceased_new'] = deceased_new_list

time

#csv 파일 저장
import csv

time.to_csv("./drive/My Drive/time_modified.csv")

"""# 1. 신규 확진자
## 신규 확진자 최대치 : 813 명
## 신규 확진자 최대인 날짜 : 2020-02-29
"""

# 신규 확진자 최대치와 날짜

max_new_confirmed_num = time['confirmed_new'].max()
max_new_confirmed_date = time['date'][time['confirmed_new'].idxmax()]
print('신규 확진자 최대치 :',max_new_confirmed_num,"명")  # 신규 확진자 최대치 : 813 명
print('신규 확진자 최대인 날짜 :',max_new_confirmed_date) # 신규 확진자 최대인 날 : 2020-02-29

"""# 2. 신규 사망자 
## 신규 사망자 최대치 : 9 명
## 신규 사망자 최대인 날짜 : 2020-03-24
"""

# 신규 사망자 최대치와 날짜


max_new_deceased_num = time['deceased_new'].max()
max_new_deceased_date = time['date'][time['deceased_new'].idxmax()]
print('신규 사망자 최대치 :',max_new_deceased_num,'명')  # 신규 사망자 최대치 : 9 명
print('신규 사망자 최대인 날짜 :',max_new_deceased_date) #  신규 사망자 최대인 날 : 2020-03-24

"""# 3. 신규 검사자 수
## 신규 검사자 최대치 : 18199 명
## 신규 검사자 최대인 날짜 : 2020-03-06
"""

# 신규 검사자 최대치와 날짜

max_new_test_num = time['test_new'].max()
max_new_test_date = time['date'][time['test_new'].idxmax()]
print('신규 검사자 최대치 :',max_new_test_num,'명')  # 신규 검사자 최대치 : 18199 명
print('신규 검사자 최대인 날짜 :',max_new_test_date) # 신규 검사자 최대인 날짜 : 2020-03-06

# Commented out IPython magic to ensure Python compatibility.
# 한글 폰트 불러오기

!apt -qq -y install fonts-nanum > /dev/null

import matplotlib.font_manager as fm

fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'

font = fm.FontProperties(fname=fontpath, size=9)

fm._rebuild()

# 그래프에 retina display 적용

# %config InlineBackend.figure_format = 'retina'

# Colab 의 한글 폰트 설정

plt.rc('font', family='NanumBarunGothic')

"""# 4. 신규 사망자 및 신규 확진자 변화 추이"""

# 신규 확진자 최대치 : 813 명
# 신규 확진자 최대인 날짜 : 2020-02-29
# 신규 사망자 최대치 : 9 명
# 신규 사망자 최대인 날짜 : 2020-03-24

ax = time.plot(kind='line', x='date', y='deceased_new', color='Red', figsize=(20,5), rot=90, label='신규 사망자')
ax2 = time.plot(kind='line', x='date', y='confirmed_new', color='Green', ax=ax, label='신규 확진자')

ax.set_xlabel('날짜', fontsize=20)
ax.set_ylabel('인원 수', fontsize=20)
plt.title('신규 확진자 및 신규 사망자 현황', fontsize=25)
# plt.legend(['신규 사망자 수', '신규 확진자 수', '신규 검사자 수'], loc=2, fontsize=15)
plt.tight_layout()
# plt.xticks(rotation=90)
plt.show()

"""# 5. 신규 검사자 수 변화 추이"""

# 신규 검사자 최대치 : 18199 명
# 신규 검사자 최대인 날짜 : 2020-03-06

ax = time.plot(kind='line', x='date', y='test_new', color='blue', figsize=(20,5), title='신규 검사자 수', rot=90, label='신규 검사자 수')

ax.set_xlabel('날짜', fontsize=20)
ax.set_ylabel('인원 수', fontsize=20)
plt.title('신규 검사자 수', fontsize=25)
plt.tight_layout()
plt.show()