# -*- coding: utf-8 -*-
"""time_age.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLh9VfiS82V_6Hvu4cxIhtF-AV7Hx-ok
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pylab as py

timeage = pd.read_csv('./drive/My Drive/Colab Notebooks/Warmingup_Project/corona_visualization/TimeAge.csv')
timeage

timeage[timeage['age'] == '10s']

"""# 9. 연령별 누적 확진자 수, 누적 사망자 수"""

timeage['age'].unique() # ['0s', '10s', '20s', '30s', '40s', '50s', '60s', '70s', '80s']

timeage['age'].isnull().sum(fw) # 결측치 없음

# 연령대별 마지막 행의 확진자수와 사망자수만 출력

timeage_df = timeage.drop_duplicates(['age'], keep='last')
timeage_df

# 행번호 재배열

new_index = []
for i in range(len(timeage_df.index)):
    new_index.append(i)
timeage_df.index = new_index
timeage_df

# 연령대별 사망률

print('0대의 사망률은:',timeage_df['deceased'][0] / timeage_df['confirmed'][0] * 100,'%')
print('10대의 사망률은:',timeage_df['deceased'][1] / timeage_df['confirmed'][1] * 100,'%')
print('20대의 사망률은:',timeage_df['deceased'][2] / timeage_df['confirmed'][2] * 100,'%')
print('30대의 사망률은:',timeage_df['deceased'][3] / timeage_df['confirmed'][3] * 100,'%')
print('40대의 사망률은:',timeage_df['deceased'][4] / timeage_df['confirmed'][4] * 100,'%')
print('50대의 사망률은:',timeage_df['deceased'][5] / timeage_df['confirmed'][5] * 100,'%')
print('60대의 사망률은:',timeage_df['deceased'][6] / timeage_df['confirmed'][6] * 100,'%')
print('70대의 사망률은:',timeage_df['deceased'][7] / timeage_df['confirmed'][7] * 100,'%')
print('80대의 사망률은:',timeage_df['deceased'][8] / timeage_df['confirmed'][8] * 100,'%')